### ISSUE TITLE
What pin on the MKR1000

### ISSUE THREAD

**Issue by karmaecrivain94** [claudeheintz/LXSAMD21DMX#2]
I'm trying to get this library to work with an MKR1000 and a MAX485 module, without any form of success. By default, without modifying the library and by using the DMXFadeTest.ino sketch, what pins should I hook up the `DI` pin of the MAX485 module to? D4?

**Comment by claudeheintz** [comment]
The circuit is listed shown in the LXSAMD21DMX.h file in the src folder of the library.

The DMXFadeTest.ino sketch does not use a direction pin.   So,  you can simply wire pins 2 and 3 of the MAX485 to v+ to hold them high.

Or, you can wire as shown in  LXSAMD21DMX.h where pins 2 and 3 of the MAX485 are connected to pin 3 of the MKR1000 and add the line:

SAMD21DMX.setDirectionPin(3);

just before line 20, "SAMD21DMX.startOutput();".
